{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.mazur;

  # Generate config.yaml from module options and freeze it in the Nix store
  # (immutable, just like the source code).  preStart copies it into the mazur
  # home directory so the agent can read it, but the canonical copy stays
  # read-only in /nix/store.
  configFile = pkgs.writeText "mazur-config.yaml" ''
    # auto-mazur configuration (generated by NixOS — do not edit on disk,
    # change flake/flake.nix instead and redeploy)

    # LLM endpoint — vLLM on the GPU machine, reached over Tailscale.
    # No authentication required: vLLM is reachable only via Tailscale.
    model:       "${cfg.model}"
    api_base:    "${cfg.vllmUrl}/v1"
    max_retries: 3

    # Context window must be >= 100 000 tokens.
    context_length_tokens: ${toString cfg.contextLengthTokens}

    # Storage — everything the agent produces lives under its home directory.
    workspace_root: "/home/mazur/workspace"
    db_path:        "/home/mazur/agent.db"

    # Tool limits
    command_timeout_seconds: 300
    max_output_bytes:        102400
    max_read_bytes:          102400
    max_read_chars:          30000
    max_read_lines:          100

    # Worker session
    max_actions_per_session:          200
    max_consecutive_errors:           5
    context_compress_threshold_tokens: 0   # auto: 60% of context_length_tokens

    # Executive
    max_executive_queries: 10

    # Task loop
    max_task_attempts: 3

    # Consolidation schedule (ticks)
    checkpoint_interval:      50
    journal_interval:         500
    reflection_interval:      2000
    weekly_summary_interval:  5000
    archive_interval:         50000

    # Health checks
    stuck_detection_window:   5
    failure_streak_threshold: 10
    neglect_threshold_ticks:  5000
  '';

in {
  # ============================================================================
  # Module options
  # ============================================================================
  options.services.mazur = {
    enable = mkEnableOption "Mazur autonomous LLM agent daemon";

    package = mkOption {
      type        = types.package;
      description = "The auto-mazur Python package (built from the repo by the flake).";
    };

    vllmUrl = mkOption {
      type        = types.str;
      description = "Base URL of the vLLM server on the GPU machine (reached over Tailscale).";
      example     = "http://100.64.0.2:8000";
    };

    model = mkOption {
      type        = types.str;
      description = "Model ID as returned by GET /v1/models on the vLLM server.";
      example     = "LilaRest/gemma-4-31B-it-NVFP4-turbo";
    };

    contextLengthTokens = mkOption {
      type        = types.int;
      default     = 180000;
      description = "Context window of the model in tokens (must be >= 100 000).";
    };
  };

  # ============================================================================
  # Implementation
  # ============================================================================
  config = mkIf cfg.enable {

    # --------------------------------------------------------------------------
    # mazur — a comfortable normal user, not a jailed service account.
    # The agent has full access to its home directory and can do anything a
    # regular user can do.  It cannot, however, modify its own source code:
    # the auto-mazur package lives in /nix/store which is read-only at the OS
    # level for every user, including mazur.
    # --------------------------------------------------------------------------
    users.users.mazur = {
      isNormalUser = true;
      home         = "/home/mazur";
      createHome   = true;
      shell        = pkgs.bash;
      description  = "Mazur autonomous LLM agent";
      # No extraGroups → no sudo, no wheel, no special privileges
    };
    users.groups.mazur = {};

    # Let the mazur user interact with the Nix daemon so that
    # `nix-shell -p <pkg>` and `nix run` work inside the service.
    nix.settings.allowed-users = [ "mazur" ];

    # --------------------------------------------------------------------------
    # Firewall — SSH inbound only; Tailscale interface handles GPU traffic
    # --------------------------------------------------------------------------
    networking.firewall = {
      enable          = true;
      allowedTCPPorts = [ 22 ];
    };

    # --------------------------------------------------------------------------
    # Systemd service — simple and permissive, but auto-restarting
    #
    # Restart = "always":  even if the agent signals its own process, systemd
    # brings it back after RestartSec.  Because mazur is not in the wheel/sudo
    # group, it cannot run `systemctl stop mazur` — only root can stop the
    # service.  Combined these two properties make the daemon resilient against
    # accidental (or deliberate) self-shutdown by the agent.
    # --------------------------------------------------------------------------
    systemd.services.mazur = {
      description   = "Mazur autonomous LLM agent daemon";
      documentation = [ "https://github.com/AlePur/auto-mazur" ];

      wantedBy = [ "multi-user.target" ];
      after    = [ "network-online.target" "nss-user-lookup.target" "tailscaled.service" ];
      wants    = [ "network-online.target" "tailscaled.service" ];

      # Runs as root before privilege-drop: installs the immutable config
      # snapshot into the mazur home directory and ensures the workspace exists.
      preStart = ''
        install -m 600 -o mazur -g mazur \
          ${configFile} /home/mazur/config.yaml
        mkdir -p /home/mazur/workspace
        chown mazur:mazur /home/mazur/workspace
      '';

      serviceConfig = {
        Type  = "simple";
        User  = "mazur";
        Group = "mazur";

        # The entry point is the wrapper script that buildPythonApplication
        # places in the package's bin/.  The package itself is at an immutable
        # /nix/store path — the mazur user executes it but cannot write to it.
        ExecStart        = "${cfg.package}/bin/auto-mazur --config /home/mazur/config.yaml";
        WorkingDirectory = "/home/mazur";

        Environment = [
          "HOME=/home/mazur"
        ];

        # Auto-restart so the agent cannot permanently shut itself down.
        Restart    = "always";
        RestartSec = "10s";

        # preStart above needs root to chown; ExecStart drops to mazur.
        PermissionsStartOnly = true;
      };
    };
  };
}
