{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.mazur;

  # Generate config.yaml from module options and freeze it in the Nix store
  # (immutable, just like the source code).  preStart copies it into the mazur
  # state directory so the agent can read it, but the canonical copy stays
  # read-only in /nix/store.
  configFile = pkgs.writeText "mazur-config.yaml" ''
    # auto-mazur configuration (generated by NixOS — do not edit on disk,
    # change flake/flake.nix instead and redeploy)

    # LLM endpoint — vLLM on the GPU machine, reached over Tailscale.
    # No authentication required: vLLM is reachable only via Tailscale.
    model:       "${cfg.model}"
    api_base:    "${cfg.vllmUrl}/v1"
    max_retries: 3

    # Context window must be >= 100 000 tokens.
    context_length_tokens: ${toString cfg.contextLengthTokens}

    # Storage — two-user separation:
    #   store_root:     daemon-only state (checkpoints, journals, audit, knowledge)
    #   workspace_root: agent work area (shell/read/write tools run here)
    #   db_path:        SQLite DB (owned by mazur, WAL-mode concurrent reads OK)
    store_root:     "/var/lib/mazur"
    workspace_root: "/home/mazur-worker"
    db_path:        "/var/lib/mazur/agent.db"

    # User separation — shell/read/write tools execute as this user via sudo.
    # The worker user cannot access /var/lib/mazur (the store).
    worker_user: "mazur-worker"

    # Tool limits
    command_timeout_seconds: 300
    max_output_bytes:        102400
    max_read_bytes:          102400
    max_read_chars:          30000
    max_read_lines:          100

    # Worker session
    max_actions_per_session:          200
    max_consecutive_errors:           5
    context_compress_threshold_tokens: 0   # auto: 60% of context_length_tokens

    # Executive
    max_executive_queries: 10

    # Task loop
    max_task_attempts: 3

    # Consolidation schedule (ticks)
    checkpoint_interval:      50
    journal_interval:         500
    reflection_interval:      2000
    weekly_summary_interval:  5000
    archive_interval:         50000

    # Health checks
    stuck_detection_window:   5
    failure_streak_threshold: 10
    neglect_threshold_ticks:  5000

    gateway_enabled: true
    gateway_port: 7878
  '';

in {
  # ============================================================================
  # Module options
  # ============================================================================
  options.services.mazur = {
    enable = mkEnableOption "Mazur autonomous LLM agent daemon";

    package = mkOption {
      type        = types.package;
      description = "The auto-mazur Python package (built from the repo by the flake).";
    };

    vllmUrl = mkOption {
      type        = types.str;
      description = "Base URL of the vLLM server on the GPU machine (reached over Tailscale).";
      example     = "http://100.64.0.2:8000";
    };

    model = mkOption {
      type        = types.str;
      description = "Model ID as returned by GET /v1/models on the vLLM server.";
      example     = "LilaRest/gemma-4-31B-it-NVFP4-turbo";
    };

    contextLengthTokens = mkOption {
      type        = types.int;
      default     = 180000;
      description = "Context window of the model in tokens (must be >= 100 000).";
    };
  };

  # ============================================================================
  # Implementation — Two-user privilege separation
  #
  #   mazur        → daemon user.  Runs the agent loop, owns /var/lib/mazur
  #                  (store, DB, audit, config).  Cannot be logged into.
  #
  #   mazur-worker → unprivileged normal user.  Shell/read/write tools execute
  #                  as this user.  Owns /home/mazur-worker (the workspace).
  #                  Cannot access /var/lib/mazur.
  #
  # The daemon (mazur) uses passwordless sudo to run commands as mazur-worker.
  # The agent can never read, modify, or delete its own internal state
  # (checkpoints, journals, knowledge, DB, audit logs) because those files
  # live in /var/lib/mazur which mazur-worker has no access to.
  # ============================================================================
  config = mkIf cfg.enable {

    # --------------------------------------------------------------------------
    # mazur — the daemon user (system account, no login shell, no home)
    # --------------------------------------------------------------------------
    users.users.mazur = {
      isSystemUser = true;
      group        = "mazur";
      # Member of mazur-worker group so the daemon can traverse and read
      # the workspace for gateway /files requests (mode 750, group r-x).
      extraGroups  = [ "mazur-worker" ];
      home         = "/var/lib/mazur";
      createHome   = false;  # systemd StateDirectory handles this
      shell        = pkgs.shadow;  # nologin — daemon only
      description  = "Mazur autonomous LLM agent daemon";
    };
    users.groups.mazur = {};

    # --------------------------------------------------------------------------
    # mazur-worker — the agent's hands.  A normal user with a rich CLI toolkit.
    # The agent's shell(), read_file(), and write_file() tools all execute as
    # this user.  It has no special privileges and cannot access the store.
    # --------------------------------------------------------------------------
    users.users.mazur-worker = {
      isNormalUser = true;
      home         = "/home/mazur-worker";
      createHome   = true;
      shell        = pkgs.bash;
      description  = "Mazur agent worker (tool execution sandbox)";
      # No extraGroups → no sudo, no wheel, no special privileges

      # Packages available in mazur-worker's PATH.  The agent works almost
      # entirely through the shell() tool so a rich set of CLI tools matters.
      packages = with pkgs; [
        # Core utilities (not always present on minimal NixOS systems)
        coreutils findutils diffutils gnugrep gnused gawk which

        # Fast search & directory navigation
        ripgrep fd tree file

        # Structured data wrangling
        jq yq-go

        # Network / HTTP
        curl wget

        # Version control
        git

        # Archive & compression
        unzip zip gnutar gzip bzip2 xz

        # Process / system inspection
        procps lsof

        # General scripting helpers
        python3 bc patch
      ];
    };
    users.groups.mazur-worker = {};

    # --------------------------------------------------------------------------
    # Sudoers — let mazur run any command as mazur-worker, without a password.
    # This is how the daemon drops privileges for tool execution.
    # --------------------------------------------------------------------------
    security.sudo.extraRules = [
      {
        users    = [ "mazur" ];
        runAs    = "mazur-worker";
        commands = [
          { command = "ALL"; options = [ "NOPASSWD" ]; }
        ];
      }
    ];

    # Let the mazur-worker user interact with the Nix daemon so that
    # `nix-shell -p <pkg>` and `nix run` work inside tool calls.
    nix.settings.allowed-users = [ "mazur-worker" ];

    # --------------------------------------------------------------------------
    # Firewall — SSH inbound only; Tailscale interface handles GPU traffic
    # --------------------------------------------------------------------------
    networking.firewall = {
      enable          = true;
      allowedTCPPorts = [ 22 ];
    };

    # --------------------------------------------------------------------------
    # Systemd service
    #
    # Restart = "always":  even if the agent kills its own process, systemd
    # brings it back after RestartSec.  mazur-worker is not in the wheel/sudo
    # group, so it cannot run `systemctl stop mazur` — only root can stop the
    # service.  Combined these two properties make the daemon resilient against
    # accidental (or deliberate) self-shutdown by the agent.
    # --------------------------------------------------------------------------
    systemd.services.mazur = {
      description   = "Mazur autonomous LLM agent daemon";

      # bash must be in PATH; sudo is reached via /run/wrappers (the NixOS
      # setuid-wrapper directory) — pkgs.sudo from the store never has the
      # setuid bit set and would fail with "must be owned by uid 0".
      path = [ pkgs.bash "/run/wrappers" ];
      documentation = [ "https://github.com/AlePur/auto-mazur" ];

      wantedBy = [ "multi-user.target" ];
      after    = [ "network-online.target" "nss-user-lookup.target" "tailscaled.service" ];
      wants    = [ "network-online.target" "tailscaled.service" ];

      # Runs as root before privilege-drop: installs the immutable config
      # and ensures both the store and workspace directories exist with
      # correct ownership.
      preStart = ''
        # Store directory (owned by mazur, not accessible by mazur-worker)
        install -d -m 750 -o mazur -g mazur /var/lib/mazur
        install -m 600 -o mazur -g mazur \
          ${configFile} /var/lib/mazur/config.yaml

        # Workspace directory (owned by mazur-worker)
        install -d -m 750 -o mazur-worker -g mazur-worker /home/mazur-worker
      '';

      serviceConfig = {
        Type  = "simple";
        User  = "mazur";
        Group = "mazur";

        # systemd manages /var/lib/mazur as the state directory; it is
        # created automatically with the right ownership on first start.
        StateDirectory    = "mazur";
        StateDirectoryMode = "0750";

        # The entry point is the wrapper script that buildPythonApplication
        # places in the package's bin/.  The package itself is at an immutable
        # /nix/store path — neither mazur nor mazur-worker can write to it.
        ExecStart        = "${cfg.package}/bin/auto-mazur --config /var/lib/mazur/config.yaml";
        WorkingDirectory = "/var/lib/mazur";

        Environment = [
          "HOME=/var/lib/mazur"
        ];

        # Auto-restart so the agent cannot permanently shut itself down.
        Restart    = "always";
        RestartSec = "10s";

        # preStart above needs root to chown; ExecStart drops to mazur.
        PermissionsStartOnly = true;
      };
    };
  };
}
